// <auto-generated />
using System;
using AITimesheet.TimesheetService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AITimesheet.TimesheetService.Migrations
{
    [DbContext(typeof(TimesheetDbContext))]
    [Migration("20260713193157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AITimesheet.TimesheetService.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("EstimatedHours")
                        .HasColumnType("double precision");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("AITimesheet.TimesheetService.Entities.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TimesheetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetId")
                        .IsUnique();

                    b.ToTable("approvals", (string)null);
                });

            modelBuilder.Entity("AITimesheet.TimesheetService.Entities.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalAccountId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("connections", (string)null);
                });

            modelBuilder.Entity("AITimesheet.TimesheetService.Entities.Timesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiWeeklySummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("WeekEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("timesheets", (string)null);
                });

            modelBuilder.Entity("AITimesheet.TimesheetService.Entities.TimesheetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DevelopmentHours")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<double>("Hours")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<double>("MeetingHours")
                        .HasColumnType("double precision");

                    b.Property<double>("ReviewHours")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TimesheetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetId");

                    b.ToTable("timesheet_entries", (string)null);
                });

            modelBuilder.Entity("AITimesheet.TimesheetService.Entities.Approval", b =>
                {
                    b.HasOne("AITimesheet.TimesheetService.Entities.Timesheet", "Timesheet")
                        .WithOne("Approval")
                        .HasForeignKey("AITimesheet.TimesheetService.Entities.Approval", "TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("AITimesheet.TimesheetService.Entities.TimesheetEntry", b =>
                {
                    b.HasOne("AITimesheet.TimesheetService.Entities.Timesheet", "Timesheet")
                        .WithMany("Entries")
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("AITimesheet.TimesheetService.Entities.Timesheet", b =>
                {
                    b.Navigation("Approval");

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
