import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { TimesheetApi } from '../api/timesheetApi';
import { describeApiError } from '../api/client';
import TimesheetTable from '../components/TimesheetTable';
import type { Timesheet } from '../types';

/** Step 5–6: the employee reviews AI-generated entries, edits them, then submits. */
export default function TimesheetReview() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [sheet, setSheet] = useState<Timesheet | null>(null);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    if (!id) return;
    setLoading(true);
    try {
      setSheet(await TimesheetApi.getById(id));
      setError('');
    } catch (err) {
      setError(describeApiError(err, 'Could not load this timesheet.'));
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => { void load(); }, [load]);

  if (loading) return <p className="muted">Loading timesheet…</p>;
  if (error && !sheet) return <div className="card card-error" role="alert">{error}</div>;
  if (!sheet) return <p className="muted">Timesheet not found.</p>;

  const editable = sheet.status === 'Generated' || sheet.status === 'Draft';

  const saveEntry = async (entryId: string, hours: number, description: string) => {
    try {
      await TimesheetApi.updateEntry(sheet.id, entryId, hours, description);
      await load();
    } catch (err) {
      setError(describeApiError(err, 'Could not save that entry.'));
    }
  };

  const submit = async () => {
    setSubmitting(true);
    try {
      await TimesheetApi.submit(sheet.id);
      await load();
    } catch (err) {
      setError(describeApiError(err, 'Could not submit this timesheet.'));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <>
      <div className="page-header">
        <span className="eyebrow">Step 5–6 · Review &amp; Submit</span>
        <h1>Week of {sheet.weekStartDate}</h1>
        <p>
          <span className={`status-pill status-${sheet.status}`}>{sheet.status}</span>
          <span className="muted" style={{ marginLeft: 10 }}>{sheet.totalHours}h total</span>
        </p>
      </div>

      {error && <div className="card card-error" role="alert">{error}</div>}

      {sheet.weeklySummary && (
        <div className="card card-accent">
          <strong className="card-accent-title">AI Weekly Summary</strong>
          <p style={{ margin: '6px 0 0', fontSize: 14 }}>{sheet.weeklySummary}</p>
        </div>
      )}

      {/* These prompts were generated by the AI/fallback engine all along but were
          discarded before ever reaching the screen. */}
      {sheet.missingHourPrompts.length > 0 && (
        <div className="card card-warn">
          <strong className="card-warn-title">Days that look light</strong>
          <ul className="prompt-list">
            {sheet.missingHourPrompts.map((prompt, i) => <li key={i}>{prompt}</li>)}
          </ul>
        </div>
      )}

      <div className="card">
        <TimesheetTable entries={sheet.entries} editable={editable} onSave={saveEntry} />
      </div>

      <div style={{ marginTop: 16, display: 'flex', gap: 10 }}>
        {editable && (
          <button className="btn btn-accent" onClick={submit} disabled={submitting}>
            {submitting ? 'Submitting…' : 'Submit for approval'}
          </button>
        )}
        <button className="btn btn-outline" onClick={() => navigate('/')}>Back to dashboard</button>
      </div>
    </>
  );
}
